sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=test
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - g++-4.8
    - chromium-chromedriver
  chrome: stable
cache:
  directories: node_modules
before_install:
  - npm i -g npm@latest
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run build_client
  - npm start &