language: node_js
node_js:
  - "8"
env:
  global:
    - CXX=g++-4.8
    - NODE_ENV=test
addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-4.8
    - g++-4.8
  chrome: stable
before_install:
 - sudo apt-get update
 - sudo apt-get install chromium-chromedriver
before_script:
  - "export PATH=$PATH:/usr/lib/chromium-browser/"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "npm run build_client && (npm start &)"